=== twilio-labs/socless_apb/dist/schemas/playbook.json
{
    "$id": "http://socless-apb-validator.socless/playbook#",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "Playbook": {
            "description": "Playbook name. Must be alphanumeric",
            "type": "string",
            "pattern": "^[A-Za-z0-9]{1,}$"
        },
        "Comment": {
            "type": "string"
        },
        "StartAt": {
            "type": "string"
        },
        "States": {
            "type": "object",
            "propertyNames": {
                "type": "string",
                "pattern": "^[a-zA-Z0-9_]{1,80}$"
            },
            "patternProperties": {
                "^[a-zA-Z0-9_]{1,80}$": {
                    "$ref": "http://socless-apb-validator.socless/state#"
                }
            },
            "additionalProperties": false
        },
        "Version": {
            "type": "string"
        },
        "TimeoutSeconds": {
            "type": "integer",
            "minimum": 0
        },
        "Decorators": {
            "$ref": "http://socless-apb-validator.socless/decorators#"
        }
    },
    "required": ["Playbook", "StartAt", "States"],
    "additionalProperties": false
}

=== twilio-labs/socless_apb/test/mocks/playbooks/pb_parallel_and_interaction/playbook.json
{
  "Playbook": "CheckUserHappiness",
  "Comment": "Sample Playbook to Geolocate an IP",
  "StartAt": "New_Interaction_State",
  "States": {
    "New_Interaction_State": {
      "Type": "Interaction",
      "Resource": "${{self:custom.slack.PromptForConfirmation}}",
      "Parameters": {
        "no_text": "No",
        "prompt_text": "Are you happy?",
        "receiver": "Slack_User_For_Response",
        "target": "$.results.Validate_Username.name",
        "target_type": "user",
        "text": "Hi, are you happy?",
        "yes_text": "Yes"
      },
      "Next": "Slack_User_For_Response"
    },
    "Slack_User_For_Response": {
      "Type": "Task",
      "Parameters": {
        "no_text": "No",
        "prompt_text": "Are you happy?",
        "receiver": "Await_User_Response",
        "target": "$.results.Validate_Username.name",
        "target_type": "user",
        "text": "Hi, are you happy?",
        "yes_text": "Yes"
      },
      "Catch": [
        {
          "ErrorEquals": ["States.ALL"],
          "Next": "Is_User_Happy"
        }
      ],
      "Retry": [
        {
          "ErrorEquals": ["ConnectionError"],
          "IntervalSeconds": 30,
          "MaxAttempts": 2,
          "BackoffRate": 2
        }
      ],
      "Resource": "${{self:custom.slack.PromptForConfirmation}}",
      "Next": "Await_User_Response"
    },
    "Await_User_Response": {
      "Type": "Task",
      "Resource": "${{self:custom.core.AwaitMessageResponseActivity}}",
      "Retry": [
        {
          "ErrorEquals": [
            "Lambda.AWSLambdaException",
            "Lambda.SdkClientException"
          ],
          "IntervalSeconds": 2,
          "MaxAttempts": 6,
          "BackoffRate": 2
        }
      ],
      "Next": "Is_User_Happy"
    },
    "Is_User_Happy": {
      "Type": "Choice",
      "Choices": [
        {
          "Variable": "$.results.result",
          "StringEquals": "false",
          "Next": "User_Is_Not_Happy"
        }
      ],
      "Default": "User_Is_Happy"
    },
    "User_Is_Happy": {
      "Type": "Pass",
      "Next": "Celebrate_With_User"
    },
    "Celebrate_With_User": {
      "Type": "Task",
      "Parameters": {
        "message_template": "I'm happy too! Yay!",
        "target": "user",
        "target_type": "channel"
      },
      "Resource": "${{self:custom.slack.SendMessage}}",
      "Next": "Mark_As_Success"
    },
    "Mark_As_Success": {
      "Type": "Succeed"
    },
    "User_Is_Not_Happy": {
      "Type": "Pass",
      "Next": "Parallel_Cheer_User_Up"
    },
    "Parallel_Cheer_User_Up": {
      "Type": "Parallel",
      "Next": "End_Cheer_Up",
      "Branches": [
        {
          "StartAt": "Slack_User_Happiness",
          "States": {
            "Slack_User_Happiness": {
              "Type": "Task",
              "Parameters": {
                "message_template": "I'm happy too! Yay!",
                "target": "user",
                "target_type": "channel"
              },
              "Resource": "${{self:custom.slack.PromptForConfirmation}}",
              "End": true
            }
          }
        },
        {
          "StartAt": "Order_Pizza_For_User",
          "States": {
            "Order_Pizza_For_User": {
              "Type": "Task",
              "Parameters": {
                "type": "bbq with bacon bits",
                "restaurant": "Five10 Pizza"
              },
              "Resource": "${{self:custom.hubgrub.PlaceOrder}}",
              "Next": "Pour_Coffee_For_User"
            },
            "Pour_Coffee_For_User": {
              "Type": "Task",
              "Parameters": {
                "how": "coffee, sugar, cream"
              },
              "Resource": "${{self:custom.iotBrewer.PourCoffee}}",
              "End": true
            }
          }
        }
      ]
    },
    "End_Cheer_Up": {
      "Type": "Task",
      "Parameters": {
        "status": "done"
      },
      "Resource": "${{self.custom.jira.TransitionIssue}}",
      "End": true
    }
  },
  "Decorators": {
    "DisableDefaultRetry": {
      "tasks": ["End_Cheer_Up"]
    }
  }
}

=== twilio-labs/socless_apb/test/mocks/playbooks/choice_validation_playbook/playbook.json
{
    "Playbook": "SoclessIteratorsIntegrationTest",
    "Comment": "Playbook to test all iterators integrations",
    "StartAt": "List_Iterator",
    "States": {
        "List_Iterator": {
            "Type": "Task",
            "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${{self:functions.ListIterator.name}}",
            "Parameters": {
                "state_name": "$.artifacts.event.details.state_name",
                "execution_id": "$.execution_id",
                "init_list": "$.artifacts.event.details.init_list",
                "init_count": "$.artifacts.event.details.init_count",
                "list_name": "$.artifacts.event.details.list_name",
                "count_name": "$.artifacts.event.details.count_name",
                "target_name": "$.artifacts.event.details.target_name"
            },
            "Next": "Has_Every_Item_Been_Processed"
        },
        "Has_Every_Item_Been_Processed": {
            "Type": "Choice",
            "Choices": [
                {
                    "Variable": "$.results.to_continue",
                    "BooleanEquals": false,
                    "Next": "Every_Item_Has_Been_Processed"
                },
                {
                    "Variable": "$.results.to_continue",
                    "BooleanEquals": true,
                    "Next": "Every_Item_Has_Not_Been_Processed"
                }
            ],
            "Default": "Every_Item_Has_Not_Been_Processed"
        },
        "Every_Item_Has_Been_Processed": {
            "Type": "Pass",
            "Next": "Set_Loop_Counter"
        },
        "Every_Item_Has_Not_Been_Processed": {
            "Type": "Pass",
            "Next": "List_Iterator"
        },
        "Set_Loop_Counter": {
            "Type": "Task",
            "Resource": "${{self:custom.core.CacheResults}}",
            "Parameters": {
                "entries": {
                    "loop_counter": "0",
                    "list_element": [
                        "element1",
                        "element2",
                        "element3",
                        "element4"
                    ]
                }
            },
            "Next": "Get_Next_Element"
        },
        "Get_Next_Element": {
            "Type": "Task",
            "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${{self:functions.LoopListElements.name}}",
            "Parameters": {
                "list_elements": "{{context.results.Set_Loop_Counter.cached.list_element}}",
                "index": "$.results._Last_Saved_Results.cached.loop_counter"
            },
            "Next": "Are_There_More_Remaining_Requests"
        },
        "Are_There_More_Remaining_Requests": {
            "Type": "Choice",
            "Choices": [
                {
                    "Variable": "$.results.Get_Next_Element.current_element",
                    "IsNull": false,
                    "Next": "Increase_Loop_Counter"
                }
            ],
            "Default": "No_More_Pending_Requests"
        },
        "Increase_Loop_Counter": {
            "Type": "Task",
            "Resource": "${{self:custom.core.CacheResults}}",
            "Parameters": {
                "entries": {
                    "loop_counter": "{{context.results.Get_Next_Element.next_element_index}}"
                }
            },
            "Next": "Get_Next_Element"
        },
        "No_More_Pending_Requests": {
            "Type": "Pass",
            "Next": "Close_Investigation"
        },
        "Close_Investigation": {
            "Type": "Task",
            "Resource": "${{self:custom.core.SetInvestigationStatus}}",
            "Parameters": {
                "investigation_id": "$.artifacts.event.investigation_id",
                "status": "closed"
            },
            "End": true
        }
    }
}

=== twilio-labs/socless_apb/test/mocks/playbooks/pb_parse_nonstring/playbook.json
{
        "Playbook": "testing_non_string_renderer",
        "Comment": "mock nonstring renderer playbook",
        "StartAt": "Celebrate_With_User",
        "States": {
            "Celebrate_With_User": {
                "Type": "Task",
                "Parameters": {
                    "message_template": "I'm happy too! Yay!",
                    "target": "U123456",
                    "target_type": "slack_id"
                },
                "Resource": "${{self:custom.slack.SendMessage}}",
                "Next": "Wait_24_Hour"
            },
            "Wait_24_Hour" : {
                "Type" : "Wait",
                "Seconds" : "apb_render_nonstring_value(${{self:custom.Wait_24_Hour_Config.${{self:provider.stage}}}})",
                "Next": "End_Cheer_Up"
            },
            "End_Cheer_Up": {
                "Type": "Task",
                "Parameters": {
                    "status": "done"
                },
                "Resource": "${{self.custom.jira.TransitionIssue}}",
                "End": true
            }
        }
    }

=== twilio-labs/socless_apb/test/mocks/playbooks/hello_world/playbook.json
{
  "Playbook": "HelloWorld",
  "Comment": "A simple playbook used for testing",
  "StartAt": "HelloWorld",
  "States": {
    "HelloWorld": {
      "Type": "Pass",
      "Next": "Choice_State"
    },
    "How_Are_You": {
      "Type": "Choice",
      "Choices": [
        {
          "Variable": "$.results.result",
          "StringEquals": "true",
          "Next": "Fine"
        },
        {
          "And": [
            {
              "Not": {
                "Variable": "$.stateinput.key",
                "IsPresent": true
              }
            }
          ],
          "Next": "Not_Fine"
        }
      ]
    },
    "Fine": {
      "Type": "Succeed"
    },
    "Not_Fine": {
      "Type": "Fail"
    }
  }
}
